set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/../cmake/toolchains/windows-clangcl-xwin.cmake")
set(VCPKG_C_FLAGS "${VCPKG_C_FLAGS} -Wno-error=incompatible-pointer-types -Wno-error=incompatible-pointer-types-discards-qualifiers")
set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -Wno-error=incompatible-pointer-types -Wno-error=incompatible-pointer-types-discards-qualifiers")
