set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(_swgme_root "${CMAKE_CURRENT_LIST_DIR}/../..")

if(DEFINED ENV{XWIN_ROOT} AND NOT "$ENV{XWIN_ROOT}" STREQUAL "")
  file(TO_CMAKE_PATH "$ENV{XWIN_ROOT}" SWGME_XWIN_ROOT)
else()
  file(TO_CMAKE_PATH "${_swgme_root}/.xwin" SWGME_XWIN_ROOT)
endif()

file(GLOB _swgme_msvc_versions LIST_DIRECTORIES true "${SWGME_XWIN_ROOT}/VC/Tools/MSVC/*")
if(NOT _swgme_msvc_versions)
  message(FATAL_ERROR "Could not find MSVC toolset under ${SWGME_XWIN_ROOT}/VC/Tools/MSVC")
endif()
list(SORT _swgme_msvc_versions)
list(GET _swgme_msvc_versions -1 SWGME_MSVC_ROOT)

file(GLOB _swgme_windows_sdk_versions LIST_DIRECTORIES true "${SWGME_XWIN_ROOT}/Windows Kits/10/Lib/*")
if(NOT _swgme_windows_sdk_versions)
  message(FATAL_ERROR "Could not find Windows SDK libraries under ${SWGME_XWIN_ROOT}/Windows Kits/10/Lib")
endif()
list(SORT _swgme_windows_sdk_versions)
list(GET _swgme_windows_sdk_versions -1 SWGME_WINDOWS_SDK_LIB_ROOT)
get_filename_component(SWGME_WINDOWS_SDK_VERSION "${SWGME_WINDOWS_SDK_LIB_ROOT}" NAME)

set(SWGME_WINDOWS_KITS_ROOT "${SWGME_XWIN_ROOT}/Windows Kits")
if(EXISTS "${SWGME_XWIN_ROOT}/WindowsKits/10/Lib")
  set(SWGME_WINDOWS_KITS_ROOT "${SWGME_XWIN_ROOT}/WindowsKits")
  set(SWGME_WINDOWS_SDK_LIB_ROOT "${SWGME_WINDOWS_KITS_ROOT}/10/Lib/${SWGME_WINDOWS_SDK_VERSION}")
endif()

set(SWGME_TOOL_WRAPPER_DIR "${_swgme_root}/cmake/toolchains/bin")
set(SWGME_XWIN_LINK_PATHS
  "/libpath:${SWGME_MSVC_ROOT}/lib/x86_64"
  "/libpath:${SWGME_WINDOWS_SDK_LIB_ROOT}/ucrt/x86_64"
  "/libpath:${SWGME_WINDOWS_SDK_LIB_ROOT}/um/x86_64"
)
string(JOIN " " SWGME_XWIN_LINK_FLAGS ${SWGME_XWIN_LINK_PATHS})

set(CMAKE_C_COMPILER clang-cl CACHE STRING "")
set(CMAKE_CXX_COMPILER clang-cl CACHE STRING "")
set(CMAKE_C_COMPILER_TARGET x86_64-pc-windows-msvc CACHE STRING "")
set(CMAKE_CXX_COMPILER_TARGET x86_64-pc-windows-msvc CACHE STRING "")
set(CMAKE_C_FLAGS_INIT "/winsysroot${SWGME_XWIN_ROOT}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_INIT "/winsysroot${SWGME_XWIN_ROOT}" CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld ${SWGME_XWIN_LINK_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=lld ${SWGME_XWIN_LINK_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_MODULE_LINKER_FLAGS_INIT "-fuse-ld=lld ${SWGME_XWIN_LINK_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_STATIC_LINKER_FLAGS_INIT "${SWGME_XWIN_LINK_FLAGS}" CACHE STRING "" FORCE)

set(CMAKE_LINKER "${SWGME_TOOL_WRAPPER_DIR}/link" CACHE FILEPATH "")
set(CMAKE_AR "${SWGME_TOOL_WRAPPER_DIR}/lib" CACHE FILEPATH "")
set(CMAKE_RANLIB ":" CACHE FILEPATH "")
set(CMAKE_RC_COMPILER "${SWGME_TOOL_WRAPPER_DIR}/rc" CACHE FILEPATH "")
set(CMAKE_MT "${SWGME_TOOL_WRAPPER_DIR}/mt" CACHE FILEPATH "")

set(CMAKE_FIND_ROOT_PATH "${SWGME_XWIN_ROOT}" CACHE STRING "")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER CACHE STRING "")
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH CACHE STRING "")
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH CACHE STRING "")
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH CACHE STRING "")
